redirects:
  - source: /.* 
    destination: /index.html 
    status: 200

headers:
  - source: '/*'
    headers:
      Strict-Transport-Security: max-age=31536000; includeSubDomains
      Content-Security-Policy: "default-src 'self'; img-src 'self' data: https://a.basemaps.cartocdn.com https://b.basemaps.cartocdn.com https://c.basemaps.cartocdn.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self' 'unsafe-inline'; connect-src 'self' http://localhost:3001 https://traccs-web.onrender.com; frame-ancestors 'none';"
      X-Frame-Options: SAMEORIGIN
      Referrer-Policy: no-referrer
      Permissions-Policy: geolocation=(self)
      X-Content-Type-Options: nosniff
